---
title: "Final Project"
author: "Hao Wang"
date: "12/10/2019"
output: html_document
---

## Introduction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(dplyr)
library(caret)
library(purrr)
library(ggplot2)
library(knitr)
library(kableExtra)
library(tidyverse)
library(car)
library(randomForest)
```

```{r}
bank = read.csv("bank-additional.csv")
```

```{r}
bank_full = read.csv("bank-additional-full.csv")
table(bank_full$job)
table(bank_full$education == "unknown")
table(bank_full$marital  == "unknown")
table(bank_full$default  == "unknown")
table(bank_full$housing  == "unknown")
table(bank_full$loan  == "unknown")
table(bank_full$y)
```

```{r}
bank_new = bank_full %>% 
  filter(bank_full$job != "unknown" & bank_full$marital != "unknown" & bank_full$education != "unknown" & bank_full$loan != "unknown" & bank_full$housing != "unknown")
```

```{r}
#set.seed(42)
idx = createDataPartition(bank_new$y, p = 0.8, list = FALSE)
bank_trn = bank_new[idx, ]
bank_tst = bank_new[-idx, ]
```

```{r}
bank_num = read.csv("bank-additional.csv")
bank_num[,] <- sapply(bank[,], as.numeric)
heatmap(x = as.matrix(bank_num))
#install.packages("car")
library(car)
full_model = lm(y ~ ., data = bank_num)
vif(full_model)
```

```{r}
names(bank_trn)
plot_1 = bank_new %>%
  ggplot(aes(x = age, col = job)) + 
  geom_density()

plot_2 = bank_new %>%
  ggplot(aes(x = education, fill = education)) + 
  geom_bar() + 
  coord_flip() +
  facet_wrap(~housing)

plot_3 = bank_new %>%
  ggplot(aes(x = cons.conf.idx, y = cons.price.idx, color = y)) + 
  geom_point()

plot_4 = bank_new %>%
  ggplot(aes(x = age, col = loan)) + 
  geom_density()

plot_5 = bank_new %>%
  ggplot(aes(x = age, col = month)) + 
  geom_density()

plot_6 = bank_new %>%
  ggplot(aes(x = age, col = contact)) + 
  geom_density()

plot_7 = bank_new %>%
  ggplot(aes(x = y, fill = education)) + 
  geom_bar() + 
  facet_wrap(~job)

plot_8 = bank_new %>%
  ggplot(aes(x = education, fill = y)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45))

plot_9 = bank_new %>%
  ggplot(aes(x = job, fill = y)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45))

plot_10 = bank_new %>%
  ggplot(aes(x = previous, fill = y)) + 
  geom_bar()
<<<<<<< HEAD
=======

plot_11 = bank_new %>%
  ggplot(aes(x = emp.var.rate, y = euribor3m)) +
  geom_point()

plot_12 = bank_new %>%
  ggplot(aes(x = emp.var.rate, y = nr.employed)) +
  geom_point()

plot_13 = bank_new %>%
  ggplot(aes(x = euribor3m, y = nr.employed)) +
  geom_point()
>>>>>>> 7e5227dd1fd09b4f069317e67fbf01cd3b0b57ed
```

```{r, print-eda-plots, fig.height = 10, fig.width = 17}
gridExtra::grid.arrange(plot_1, plot_2, plot_3, plot_4, plot_5, plot_6, plot_7, plot_8, plot_9, plot_10)
```


```{r}
bank_num = bank
bank_num[,] <- sapply(bank[,], as.numeric)
```

```{r}
rf = randomForest(y ~ ., data = bank)
```

```{r}
rf$importance
```

```{r pca}
pca = prcomp(bank_full[, c("emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed")], center = TRUE, scale = TRUE)
# mat = scale(as.matrix(bank[, c("emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed")]))
```

```{r pca scree}
evals = pca$sdev ^ 2
ggplot(mapping = aes(x = 1:length(pca$sdev), y = pca$sdev ^ 2 / sum(pca$sdev ^ 2))) +
  geom_line(color = "turquoise3", size = 1.5) + 
  geom_point(size = 5, color = "tomato", shape = 18) +
  xlab("Number of PCs") +
  ylab("Variance") + 
  ggtitle("Scree Plot")
```

```{r pca loading, fig.height = 7, fig.width = 7}
# function to create a circle
circle = function(center = c(0, 0), npoints = 100) {
    r = 1
    tt = seq(0, 2 * pi, length = npoints)
    xx = center[1] + r * cos(tt)
    yy = center[1] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}

corcir = circle(c(0, 0), npoints = 100)

# create data frame with correlations between variables and PCs
correlations = as.data.frame(cor(bank_full[, c("emp.var.rate", "cons.price.idx", "cons.conf.idx", "euribor3m", "nr.employed")], pca$x))

# data frame with arrows coordinates
arrows = data.frame(x1 = c(0, 0, 0, 0, 0), y1 = c(0, 0, 0, 0, 0), x2 = correlations$PC1, 
    y2 = correlations$PC2)

# geom_path will do open circles
ggplot() +
  geom_path(data = corcir, aes(x = x, y = y), colour = "turquoise3") + 
  geom_segment(data = arrows, aes(x = x1, y = y1, xend = x2, yend = y2), colour = "turquoise3") + 
  geom_text(data = correlations, aes(x = PC1, y = PC2, label = rownames(correlations)), color = "tomato") + 
  geom_hline(yintercept = 0, colour = "gray65") +
  geom_vline(xintercept = 0, colour = "gray65") +
  xlim(-1.1, 1.1) +
  ylim(-1.1, 1.1) +
  labs(x = "pc1 aixs", y = "pc2 axis") +
  ggtitle("Circle of correlations")
```

```{r pca transform}
pca1 = prcomp(bank_full[, c("emp.var.rate", "cons.price.idx", "euribor3m", "nr.employed")])
trans = pca1$rotation[, 1]
bank = bank %>%
  mutate(econ.idx = -(emp.var.rate * trans[1] + cons.price.idx * trans[2] + euribor3m * trans[3] + nr.employed * trans[4])) %>%
  select(-c("emp.var.rate", "cons.price.idx", "euribor3m", "nr.employed"))
bank_full = bank_full %>%
  mutate(econ.idx = -(emp.var.rate * trans[1] + cons.price.idx * trans[2] + euribor3m * trans[3] + nr.employed * trans[4])) %>%
  select(-c("emp.var.rate", "cons.price.idx", "euribor3m", "nr.employed"))
```

```{r}
histogram(bank_full$econ.idx, breaks = 100)
```







